#!/bin/bash
# Setup Instructions for Testing OAuth Login

echo "========================================="
echo "Setup Guide for OAuth Testing"
echo "========================================="

echo ""
echo "Step 1: Download Firebase Service Account Key"
echo "-------------------------------------------"
echo "1. Go to Firebase Console: https://console.firebase.google.com/"
echo "2. Select your project"
echo "3. Go to Project Settings (gear icon) > Service Accounts"
echo "4. Click 'Generate New Private Key'"
echo "5. Download the JSON file"
echo "6. Rename it to 'firebase-service-account.json'"
echo "7. Place it in: backend/src/main/resources/"

echo ""
echo "Step 2: Verify Database Configuration"
echo "-------------------------------------------"
echo "✓ Neon DB URL configured in application-dev.properties"
echo "Connection String: postgresql://neondb_owner:***@ep-damp-dust-a1zwfcow-pooler.ap-southeast-1.aws.neon.tech/neondb"

echo ""
echo "Step 3: Start Backend Server"
echo "-------------------------------------------"
echo "Run: mvn spring-boot:run"
echo "Or: ./mvnw spring-boot:run (if using Maven wrapper)"
echo "Backend will start on: http://localhost:8080"

echo ""
echo "Step 4: Get Firebase ID Token from Mobile App"
echo "-------------------------------------------"
echo "Add this code in your frontend after Google Sign In:"
echo ""
echo "  const idToken = await user.getIdToken();"
echo "  console.log('Firebase ID Token:', idToken);"
echo ""
echo "Copy the token from console logs"

echo ""
echo "Step 5: Test Login API"
echo "-------------------------------------------"
echo "Option A: Use PowerShell script"
echo "  Run: ./test-api.ps1"
echo ""
echo "Option B: Use curl"
echo "  curl -X POST http://localhost:8080/api/auth/login \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"firebaseIdToken\": \"YOUR_TOKEN_HERE\"}'"

echo ""
echo "Step 6: Verify Data Saved"
echo "-------------------------------------------"
echo "Check Neon DB:"
echo "  psql 'postgresql://neondb_owner:npg_1HpXZgi7tVLh@ep-damp-dust-a1zwfcow-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require'"
echo "  SELECT * FROM users;"
echo ""
echo "Check Firebase (Firestore currently not active, only using for Auth):"
echo "  Go to Firebase Console > Authentication > Users"

echo ""
echo "========================================="
echo "Ready to test!"
echo "========================================="
